# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2df4c5eebec5591b918e4b9b7fba69c05a06b5274f21063b6a5c6ca27e597ba6c5b76a7379683a430d778db7f32e5c57ae1e85c3e977da76a22dec88ca1e87d7

test:
  secret_key_base: 9a9d0c3541b425004adba5a256cd9d69263c8cd0d953a07bbfc882dbc6b5220f6de6f0d9a42321dbdb0df0143ac63176368f7fb26ee0e22d86f4a699df8cefff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
